name: "(T3K) T3000 perplexity tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6" # This cron schedule runs the workflow every saturday at 12pm

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-wheel: true
  t3000-model-accuracy-perplexity-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/t3000-perplexity-tests-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.ci-build-docker-image }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
